In [94]:
import pandas as pd
import numpy as np
import matplotlib as plt

pd.set_option('display.max_columns', None)

**UČITAVANJE I PRIPREMA SKUPOVA PODATAKA**

In [95]:
filenames=["Abdoulaye_Doucoure",
           "Alejandro_Garnacho",
           "Alex_Iwobi",
           "Alexis_MacAllister",
           "Amadou_Onana",
           "Andreas_Pereira",
           "Anthony_Elanga",
           "Anthony_Gordon",
           "Bernardo_Silva",
           "Billy_Gilmour",
           "Boubacar_Kamara",
           "Brennan_Johnson",
           "Bruno_Fernandes",
           "Bruno_Guimaraes",
           "Bryan_Mbeumo",
           "Bukayo_Saka",
           "Callum_Hudson",
           "Carlos_Casimiro",
           "Christian_Norgaard",
           "Cole_Palmer",
           "Conor_Gallagher",
           "Danilo_Oliveira",
           "Declan_Rice",
           "Dejan_Kulusevski",
           "Dominik_Szoboszlai",
           "Douglas_Luiz",
           "Dwight_McNeil",
           "Eberechi_Eze",
           "Edson_Alvarez",
           "Enzo_Fernandez",
           "Gabriel_Martinelli",
           "Harry_Wilson",
           "Hwang_Hee",
           "Idrissa_Gueye",
           "James_Garner",
           "James_Maddison",
           "James_McAtee",
           "Jarrod_Bowen",
           "Jefferson_Lerma",
           "Joao_Gomes",
           "Joao_Palhinha",
           "John_McGinn",
           "Jordan_Ayew",
           "Josh_Brownhill",
           "Josh_Cullen",
           "Justin_Kluivert",
           "Kai_Havertz",
           "Kobbie_Mainoo",
           "Leandro_Trossard",
           "Leon_Bailey",
           "Lewis_Cook",
           "Lucas_Lima",
           "Luis_Diaz",
           "Marcus_Rashford",
           "Marcus_Tavernier",
           "Mario_Lemina",
           "Martin_Odegaard",
           "Mateo_Kovacic",
           "Mathias_Jensen",
           "Miguel_Almiron",
           "Mohamed_Salah",
           "Moises_Caicedo",
           "Morgan_Gibbs",
           "Mousa_Diaby",
           "Mykhailo_Mudryk",
           "Orel_Mangala",
           "Pablo_Sarabia",
           "Pape_Sarr",
           "Pascal_Gros",
           "Pedro_Neto",
           "Phil_Foden",
           "Raheem_Sterling",
           "Rodrigo_Hernandez",
           "Ross_Barkley",
           "Ryan_Christie",
           "Ryan_Yates",
           "Sander_Berge",
           "Scott_McTominay",
           "Sean_Longstaff",
           "Simon_Adingra",
           "Son_Heung",
           "Tahith_Chong",
           "Tomas_Soucek",
           "Vini_Souza",
           "Vitaly_Janelt",
           "Will_Hughes",
           "Willian_Borges",
           "Youri_Tielemans",
           "Yves_Bissouma"]

dfs={}

In [96]:
for dataframe in filenames:
    df=pd.read_csv(dataframe+".csv")
    
    dfs[dataframe.split('.')[0]]=df

In [97]:
df_Doucoure=dfs['Abdoulaye_Doucoure']
df_Garnacho=dfs['Alejandro_Garnacho']
df_Iwobi=dfs['Alex_Iwobi']
df_MacAllister=dfs['Alexis_MacAllister']
df_Onana=dfs['Amadou_Onana']
df_Pereira=dfs['Andreas_Pereira']
df_Elanga=dfs['Anthony_Elanga']
df_Gordon=dfs['Anthony_Gordon']
df_Silva=dfs['Bernardo_Silva']
df_Gilmour=dfs['Billy_Gilmour']
df_Kamara=dfs['Boubacar_Kamara']
df_Johnson=dfs['Brennan_Johnson']
df_Fernandes=dfs['Bruno_Fernandes']
df_Guimaraes=dfs['Bruno_Guimaraes']
df_Mbeumo=dfs['Bryan_Mbeumo']
df__Saka=dfs['Bukayo_Saka']
df_Hudson=dfs['Callum_Hudson']
df_Casimiro=dfs['Carlos_Casimiro']
df_Norgaard=dfs['Christian_Norgaard']
df_Palmer=dfs['Cole_Palmer']
df_Gallagher=dfs['Conor_Gallagher']
df_Oliveira=dfs['Danilo_Oliveira']
df_Rice=dfs['Declan_Rice']
df_Kulusevski=dfs['Dejan_Kulusevski']
df_Szoboszlai=dfs['Dominik_Szoboszlai']
df_Luiz=dfs['Douglas_Luiz']
df_McNeil=dfs['Dwight_McNeil']
df_Eze=dfs['Eberechi_Eze']
df_Alvarez=dfs['Edson_Alvarez']
df_Fernandez=dfs['Enzo_Fernandez']
df_Martinelli=dfs['Gabriel_Martinelli']
df_Wilson=dfs['Harry_Wilson']
df_Hee=dfs['Hwang_Hee']
df_Gueye=dfs['Idrissa_Gueye']
df_Garner=dfs['James_Garner']
df_Maddison=dfs['James_Maddison']
df_McAtee=dfs['James_McAtee']
df_Bowen=dfs['Jarrod_Bowen']
df_Lerma=dfs['Jefferson_Lerma']
df_Gomes=dfs['Joao_Gomes']
df_Palhinha=dfs['Joao_Palhinha']
df_McGinn=dfs['John_McGinn']
df_Ayew=dfs['Jordan_Ayew']
df_Brownhill=dfs['Josh_Brownhill']
df_Cullen=dfs['Josh_Cullen']
df_Kluivert=dfs['Justin_Kluivert']
df_Havertz=dfs['Kai_Havertz']
df_Mainoo=dfs['Kobbie_Mainoo']
df_Trossard=dfs['Leandro_Trossard']
df_Bailey=dfs['Leon_Bailey']
df_Cook=dfs['Lewis_Cook']
df_Lima=dfs['Lucas_Lima']
df_Diaz=dfs['Luis_Diaz']
df_Rashford=dfs['Marcus_Rashford']
df_Tavernier=dfs['Marcus_Tavernier']
df_Lemina=dfs['Mario_Lemina']
df_Odegaard=dfs['Martin_Odegaard']
df_Kovacic=dfs['Mateo_Kovacic']
df_Jensen=dfs['Mathias_Jensen']
df_Almiron=dfs['Miguel_Almiron']
df_Salah=dfs['Mohamed_Salah']
df_Caicedo=dfs['Moises_Caicedo']
df_Gibbs=dfs['Morgan_Gibbs']
df_Diaby=dfs['Mousa_Diaby']
df_Mudryk=dfs['Mykhailo_Mudryk']
df_Mangala=dfs['Orel_Mangala']
df_Sarabia=dfs['Pablo_Sarabia']
df_Sarr=dfs['Pape_Sarr']
df_Gros=dfs['Pascal_Gros']
df_Neto=dfs['Pedro_Neto']
df_Foden=dfs['Phil_Foden']
df_Sterling=dfs['Raheem_Sterling']
df_Hernandez=dfs['Rodrigo_Hernandez']
df_Barkley=dfs['Ross_Barkley']
df_Christie=dfs['Ryan_Christie']
df_Yates=dfs['Ryan_Yates']
df_Berge=dfs['Sander_Berge']
df_McTominay=dfs['Scott_McTominay']
df_Longstaff=dfs['Sean_Longstaff']
df_Adingra=dfs['Simon_Adingra']
df_Heung=dfs['Son_Heung']
df_Chong=dfs['Tahith_Chong']
df_Soucek=dfs['Tomas_Soucek']
df_Souza=dfs['Vini_Souza']
df_Janelt=dfs['Vitaly_Janelt']
df_Hughes=dfs['Will_Hughes']
df_Borges=dfs['Willian_Borges']
df_Tielemans=dfs['Youri_Tielemans']
df_Bissouma=dfs['Yves_Bissouma']

In [98]:
dataframes=[df_Doucoure,
            df_Garnacho,
            df_Iwobi,
            df_MacAllister,
            df_Onana,
            df_Pereira,
            df_Elanga,
            df_Gordon,
            df_Silva,
            df_Gilmour,
            df_Kamara,
            df_Johnson,
            df_Fernandes,
            df_Guimaraes,
            df_Mbeumo,
            df_Saka,
            df_Hudson,
            df_Casimiro,
            df_Norgaard,
            df_Palmer,
            df_Gallagher,
            df_Oliveira,
            df_Rice,
            df_Kulusevski,
            df_Szoboszlai,
            df_Luiz,
            df_McNeil,
            df_Eze,
            df_Alvarez,
            df_Fernandez,
            df_Martinelli,
            df_Wilson,
            df_Hee,
            df_Gueye,
            df_Garner,
            df_Maddison,
            df_McAtee,
            df_Bowen,
            df_Lerma,
            df_Gomes,
            df_Palhinha,
            df_McGinn,
            df_Ayew,
            df_Brownhill,
            df_Cullen,
            df_Kluivert,
            df_Havertz,
            df_Mainoo,
            df_Trossard,
            df_Bailey,
            df_Cook,
            df_Lima,
            df_Diaz,
            df_Rashford,
            df_Tavernier,
            df_Lemina,
            df_Odegaard,
            df_Kovacic,
            df_Jensen,
            df_Almiron,
            df_Salah,
            df_Caicedo,
            df_Gibbs,
            df_Diaby,
            df_Mudryk,
            df_Mangala,
            df_Sarabia,
            df_Sarr,
            df_Gros,
            df_Neto,
            df_Foden,
            df_Sterling,
            df_Hernandez,
            df_Barkley,
            df_Christie,
            df_Yates,
            df_Berge,
            df_McTominay,
            df_Longstaff,
            df_Adingra,
            df_Heung,
            df_Chong,
            df_Soucek,
            df_Souza,
            df_Janelt,
            df_Hughes,
            df_Borges,
            df_Tielemans,
            df_Bissouma]

In [99]:
df_Salah.head()

,assists,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,starts,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards
0,1,0,15,0,20.2,308,0.31,0.59,0.28,1.28,9,1,0,4.9,16.6,2023-08-13T15:30:00Z,76,7,0,0,0,0,1,0,2243674,1,1,1,12.0,5,0,0,0,125,False,0
1,0,0,15,0,33.0,308,0.11,1.34,1.23,1.00,14,1,1,15.3,41.4,2023-08-19T14:00:00Z,85,3,0,1,0,0,2,0,2739755,1,1,3,79.0,5,163064,211617,48553,125,True,0
2,1,0,19,0,24.9,308,0.12,0.30,0.18,2.00,29,1,0,7.0,28.6,2023-08-27T15:30:00Z,90,15,0,0,0,0,3,0,2570086,1,2,1,16.0,5,-229297,98738,328035,125,False,0
3,0,0,26,1,23.1,308,0.07,0.87,0.80,0.66,37,0,1,18.3,45.2,2023-09-03T13:00:00Z,90,2,0,0,0,0,4,0,2505698,1,0,3,115.0,8,-122416,74612,197028,125,True,0
4,2,2,35,0,57.4,308,1.47,1.71,0.24,0.63,50,1,0,12.1,44.2,2023-09-16T11:30:00Z,90,20,0,0,0,0,5,0,2540130,1,3,1,19.0,10,-22644,117182,139826,125,False,0

In [100]:
def ubaci_ime_u_dataframe():
    for df,name in zip(dataframes,filenames):
        df["Firstname"]=name.split('_')[0]
        df["Lastname"]=name.split('_')[1]

In [101]:
def oblik():
    for df in dataframes:
        print(df.shape)

In [102]:
oblik()

(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 38)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)
(38, 36)

In [103]:
ubaci_ime_u_dataframe()

In [104]:
df_Salah.head()

,assists,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,starts,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,Firstname,Lastname
0,1,0,15,0,20.2,308,0.31,0.59,0.28,1.28,9,1,0,4.9,16.6,2023-08-13T15:30:00Z,76,7,0,0,0,0,1,0,2243674,1,1,1,12.0,5,0,0,0,125,False,0,Mohamed,Salah
1,0,0,15,0,33.0,308,0.11,1.34,1.23,1.00,14,1,1,15.3,41.4,2023-08-19T14:00:00Z,85,3,0,1,0,0,2,0,2739755,1,1,3,79.0,5,163064,211617,48553,125,True,0,Mohamed,Salah
2,1,0,19,0,24.9,308,0.12,0.30,0.18,2.00,29,1,0,7.0,28.6,2023-08-27T15:30:00Z,90,15,0,0,0,0,3,0,2570086,1,2,1,16.0,5,-229297,98738,328035,125,False,0,Mohamed,Salah
3,0,0,26,1,23.1,308,0.07,0.87,0.80,0.66,37,0,1,18.3,45.2,2023-09-03T13:00:00Z,90,2,0,0,0,0,4,0,2505698,1,0,3,115.0,8,-122416,74612,197028,125,True,0,Mohamed,Salah
4,2,2,35,0,57.4,308,1.47,1.71,0.24,0.63,50,1,0,12.1,44.2,2023-09-16T11:30:00Z,90,20,0,0,0,0,5,0,2540130,1,3,1,19.0,10,-22644,117182,139826,125,False,0,Mohamed,Salah

In [105]:
oblik()

(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)

In [106]:
def izbaci_kolone(column_names):
    for dataframe in dataframes:
        dataframe.drop(columns=column_names,inplace=True)

In [107]:
column_names=['bps',
              'bonus',
              'selected',
              'starts',
              'creativity',
              'element',
              'ict_index',
              'influence',
              'kickoff_time',
              'round',
              'threat',
              'transfers_balance',
              'transfers_in',
              'transfers_out',
              'team_a_score',
              'team_h_score',
              'value',
              'fixture',
              'was_home',
              'expected_goal_involvements',
              'penalties_saved',
              'saves']

In [108]:
izbaci_kolone(column_names)

In [109]:
df_Salah.head()

,assists,clean_sheets,expected_assists,expected_goals,expected_goals_conceded,goals_conceded,goals_scored,minutes,opponent_team,own_goals,penalties_missed,red_cards,total_points,yellow_cards,Firstname,Lastname
0,1,0,0.31,0.28,1.28,1,0,76,7,0,0,0,5,0,Mohamed,Salah
1,0,0,0.11,1.23,1.00,1,1,85,3,0,1,0,5,0,Mohamed,Salah
2,1,0,0.12,0.18,2.00,1,0,90,15,0,0,0,5,0,Mohamed,Salah
3,0,1,0.07,0.80,0.66,0,1,90,2,0,0,0,8,0,Mohamed,Salah
4,2,0,1.47,0.24,0.63,1,0,90,20,0,0,0,10,0,Mohamed,Salah

In [110]:
oblik()

(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)

**DODATNO SREDJIVANJE I KREIRANJE NOVIH KOLONA**

**1.SPAJANJE SA TABELOM TIMOVA**

In [111]:
from IPython.display import HTML

In [112]:
def mapiranje_timova(df):
    df_teams=pd.read_csv("teams.csv")
    df_teams.head(20)
    
    team_names={
    1:"Arsenal",
    2:"Aston Vila",
    3:"Bournemouth",
    4:"Brentford",
    5:"Brighton",
    6:"Burnley",
    7:"Chelsea",
    8:"Crystal Palace",
    9:"Everton",
    10:"Fulham",
    11:"Liverpool",
    12:"Luton",
    13:"Man City",
    14:"Man Utd",
    15:"Newcastle",
    16:"Nott'm Forest",
    17:"Sheffield Utd",
    18:"Spurs",
    19:"West Ham",
    20:"Wolves",
    }
    
    df["Teams"]=df["opponent_team"].map(team_names)
    
    return(df.head(10))

In [113]:
for dataframe in dataframes:
    mapiranje_timova(dataframe)

In [114]:
df_Salah.head()

,assists,clean_sheets,expected_assists,expected_goals,expected_goals_conceded,goals_conceded,goals_scored,minutes,opponent_team,own_goals,penalties_missed,red_cards,total_points,yellow_cards,Firstname,Lastname,Teams
0,1,0,0.31,0.28,1.28,1,0,76,7,0,0,0,5,0,Mohamed,Salah,Chelsea
1,0,0,0.11,1.23,1.00,1,1,85,3,0,1,0,5,0,Mohamed,Salah,Bournemouth
2,1,0,0.12,0.18,2.00,1,0,90,15,0,0,0,5,0,Mohamed,Salah,Newcastle
3,0,1,0.07,0.80,0.66,0,1,90,2,0,0,0,8,0,Mohamed,Salah,Aston Vila
4,2,0,1.47,0.24,0.63,1,0,90,20,0,0,0,10,0,Mohamed,Salah,Wolves

In [115]:
oblik()

(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)
(38, 17)

In [116]:
def ucitaj_tabelu():
    html="""
<iframe id="sofa-standings-embed-1-52186" src="https://widgets.sofascore.com/embed/tournament/1/season/52186/standings/Premier%20League?widgetTitle=Premier%20League&showCompetitionLogo=true" style=height:1112.5px!important;max-width:768px!important;width:100%!important; frameborder="0" scrolling="no"></iframe>
    <div style="font-size:12px;font-family:Arial,sans-serif;text-align:left">
      Standings provided by <a target="_blank" href="https://www.sofascore.com/">Sofascore</a>
    </div>
"""
    return(HTML(html))

In [117]:
ucitaj_tabelu()

In [118]:
def mapiranje_tezine_protivnika(df):
    fixture_rating={
    "Arsenal":5,
    "Aston Vila":5,
    "Bournemouth":3,
    "Brentford":2,
    "Brighton":3,
    "Burnley":2,
    "Chelsea":4,
    "Crystal Palace":4,
    "Everton":3,
    "Fulham":3,
    "Liverpool":5,
    "Luton":2,
    "Man City":5,
    "Man Utd":4,
    "Newcastle":4,
    "Nott'm Forest":2,
    "Sheffield Utd":2,
    "Spurs":5,
    "West Ham":4,
    "Wolves":3,
    } 
    
    df["Fixture_Rating"]=df["Teams"].map(fixture_rating)
    
    return(df.head(10))

In [119]:
for dataframe in dataframes:
    mapiranje_tezine_protivnika(dataframe)

In [120]:
df_Salah.head()

,assists,clean_sheets,expected_assists,expected_goals,expected_goals_conceded,goals_conceded,goals_scored,minutes,opponent_team,own_goals,penalties_missed,red_cards,total_points,yellow_cards,Firstname,Lastname,Teams,Fixture_Rating
0,1,0,0.31,0.28,1.28,1,0,76,7,0,0,0,5,0,Mohamed,Salah,Chelsea,4
1,0,0,0.11,1.23,1.00,1,1,85,3,0,1,0,5,0,Mohamed,Salah,Bournemouth,3
2,1,0,0.12,0.18,2.00,1,0,90,15,0,0,0,5,0,Mohamed,Salah,Newcastle,4
3,0,1,0.07,0.80,0.66,0,1,90,2,0,0,0,8,0,Mohamed,Salah,Aston Vila,5
4,2,0,1.47,0.24,0.63,1,0,90,20,0,0,0,10,0,Mohamed,Salah,Wolves,3

In [121]:
oblik()

(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)
(38, 18)

In [122]:
new_column_names=["opponent_team","Teams"]

In [123]:
izbaci_kolone(new_column_names)

In [124]:
df_Salah.head()

,assists,clean_sheets,expected_assists,expected_goals,expected_goals_conceded,goals_conceded,goals_scored,minutes,own_goals,penalties_missed,red_cards,total_points,yellow_cards,Firstname,Lastname,Fixture_Rating
0,1,0,0.31,0.28,1.28,1,0,76,0,0,0,5,0,Mohamed,Salah,4
1,0,0,0.11,1.23,1.00,1,1,85,0,1,0,5,0,Mohamed,Salah,3
2,1,0,0.12,0.18,2.00,1,0,90,0,0,0,5,0,Mohamed,Salah,4
3,0,1,0.07,0.80,0.66,0,1,90,0,0,0,8,0,Mohamed,Salah,5
4,2,0,1.47,0.24,0.63,1,0,90,0,0,0,10,0,Mohamed,Salah,3

In [125]:
oblik()

(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)
(38, 16)

**2.DELTA KOLONE**

In [126]:
def izracunaj_delta_vrednosti(df):
    #GOLOVI
    
    delta_goals_scored=df.goals_scored-df.expected_goals
    
    #print(delta_goals_scored)
    
    df["Delta_Goals"]=delta_goals_scored
    
    #ASISTENCIJE
    
    delta_assists=df.assists-df.expected_assists
    
    #print(delta_assists)
    
    df["Delta_Assists"]=delta_assists
    
    #PRIMLJENI GOLOVI
    
    delta_goals_conceded=df.expected_goals_conceded-df.goals_conceded
    
    #print(delta_goals_conceded)
    
    df["Delta_Goals_Conceded"]=delta_goals_conceded
    
    return(df.head(10))

In [127]:
for dataframe in dataframes:
    izracunaj_delta_vrednosti(dataframe)

In [128]:
df_Salah.head()

,assists,clean_sheets,expected_assists,expected_goals,expected_goals_conceded,goals_conceded,goals_scored,minutes,own_goals,penalties_missed,red_cards,total_points,yellow_cards,Firstname,Lastname,Fixture_Rating,Delta_Goals,Delta_Assists,Delta_Goals_Conceded
0,1,0,0.31,0.28,1.28,1,0,76,0,0,0,5,0,Mohamed,Salah,4,-0.28,0.69,0.28
1,0,0,0.11,1.23,1.00,1,1,85,0,1,0,5,0,Mohamed,Salah,3,-0.23,-0.11,0.00
2,1,0,0.12,0.18,2.00,1,0,90,0,0,0,5,0,Mohamed,Salah,4,-0.18,0.88,1.00
3,0,1,0.07,0.80,0.66,0,1,90,0,0,0,8,0,Mohamed,Salah,5,0.20,-0.07,0.66
4,2,0,1.47,0.24,0.63,1,0,90,0,0,0,10,0,Mohamed,Salah,3,-0.24,0.53,-0.37

In [129]:
oblik()

(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)
(38, 19)

**3.PROMENA REDOSLEDA I IMENA KOLONA**

In [130]:
def promeni_ime_kolona(df,column_names):
    df.rename(columns=column_names,inplace=True)

In [131]:
column_rename={'assists':'Assists',
              'clean_sheets':'Clean_Sheet',
              'expected_assists':'xA',
              'expected_goals':'xG',
              'expected_goals_conceded':'xGC',
              'goals_conceded':'Goals_Conceded',
              'goals_scored':'Goals_Scored',
              'minutes':'Minutes',
              'own_goals':'Own_Goals',
              'penalties_missed':'Penalites_Missed',
              'red_cards':'Red_Cards',
              'total_points':'Points',
              'yellow_cards':'Yellow_Cards'
             }

In [132]:
for dataframe in dataframes:
    promeni_ime_kolona(dataframe,column_rename)

In [133]:
df_Salah.head()

,Assists,Clean_Sheet,xA,xG,xGC,Goals_Conceded,Goals_Scored,Minutes,Own_Goals,Penalites_Missed,Red_Cards,Points,Yellow_Cards,Firstname,Lastname,Fixture_Rating,Delta_Goals,Delta_Assists,Delta_Goals_Conceded
0,1,0,0.31,0.28,1.28,1,0,76,0,0,0,5,0,Mohamed,Salah,4,-0.28,0.69,0.28
1,0,0,0.11,1.23,1.00,1,1,85,0,1,0,5,0,Mohamed,Salah,3,-0.23,-0.11,0.00
2,1,0,0.12,0.18,2.00,1,0,90,0,0,0,5,0,Mohamed,Salah,4,-0.18,0.88,1.00
3,0,1,0.07,0.80,0.66,0,1,90,0,0,0,8,0,Mohamed,Salah,5,0.20,-0.07,0.66
4,2,0,1.47,0.24,0.63,1,0,90,0,0,0,10,0,Mohamed,Salah,3,-0.24,0.53,-0.37

In [134]:
def promeni_redosled_kolona(new_column_order):
    for df in dataframes:
        df=df[new_column_order]

In [137]:
column_order=['Firstname',
              'Lastname',
              'Fixture_Rating',
              'Minutes',
              'Goals_Scored',
              'xG',
              'Delta_Goals',
              'Assists',
              'xA',
              'Delta_Assists',
              'Goals_Conceded',
              'xGC',
              'Delta_Goals_Conceded',
              'Clean_Sheet',
              'Own_Goals',
              'Penalites_Missed',
              'Yellow_Cards',
              'Red_Cards',
              'Points']

In [138]:
promeni_redosled_kolona(column_order)

In [139]:
def napravi_ciljni_atribut():
    for df in dataframes:
        df['Next_Points'] = df['Points'].shift(-1) #вредност поена играца у наредном колу и она се предвиђа
        
        for column in df.select_dtypes(include='number').columns:     
                df[f'Running_{column}'] = df[column].rolling(window=4, min_periods=1).mean() #просек тренутног и претходна 3 кола

In [140]:
napravi_ciljni_atribut()

In [141]:
df_Salah.head()

,Assists,Clean_Sheet,xA,xG,xGC,Goals_Conceded,Goals_Scored,Minutes,Own_Goals,Penalites_Missed,Red_Cards,Points,Yellow_Cards,Firstname,Lastname,Fixture_Rating,Delta_Goals,Delta_Assists,Delta_Goals_Conceded,Next_Points,Running_Assists,Running_Clean_Sheet,Running_xA,Running_xG,Running_xGC,Running_Goals_Conceded,Running_Goals_Scored,Running_Minutes,Running_Own_Goals,Running_Penalites_Missed,Running_Red_Cards,Running_Points,Running_Yellow_Cards,Running_Fixture_Rating,Running_Delta_Goals,Running_Delta_Assists,Running_Delta_Goals_Conceded,Running_Next_Points
0,1,0,0.31,0.28,1.28,1,0,76,0,0,0,5,0,Mohamed,Salah,4,-0.28,0.69,0.28,5.0,1.000000,0.00,0.3100,0.280000,1.280000,1.00,0.000000,76.000000,0.0,0.000000,0.0,5.00,0.0,4.000000,-0.2800,0.690000,0.280000,5.00
1,0,0,0.11,1.23,1.00,1,1,85,0,1,0,5,0,Mohamed,Salah,3,-0.23,-0.11,0.00,5.0,0.500000,0.00,0.2100,0.755000,1.140000,1.00,0.500000,80.500000,0.0,0.500000,0.0,5.00,0.0,3.500000,-0.2550,0.290000,0.140000,5.00
2,1,0,0.12,0.18,2.00,1,0,90,0,0,0,5,0,Mohamed,Salah,4,-0.18,0.88,1.00,8.0,0.666667,0.00,0.1800,0.563333,1.426667,1.00,0.333333,83.666667,0.0,0.333333,0.0,5.00,0.0,3.666667,-0.2300,0.486667,0.426667,6.00
3,0,1,0.07,0.80,0.66,0,1,90,0,0,0,8,0,Mohamed,Salah,5,0.20,-0.07,0.66,10.0,0.500000,0.25,0.1525,0.622500,1.235000,0.75,0.500000,85.250000,0.0,0.250000,0.0,5.75,0.0,4.000000,-0.1225,0.347500,0.485000,7.00
4,2,0,1.47,0.24,0.63,1,0,90,0,0,0,10,0,Mohamed,Salah,3,-0.24,0.53,-0.37,10.0,0.750000,0.25,0.4425,0.612500,1.072500,0.75,0.500000,88.750000,0.0,0.250000,0.0,7.00,0.0,3.750000,-0.1125,0.307500,0.322500,8.25

In [142]:
dataframes[0]

,Assists,Clean_Sheet,xA,xG,xGC,Goals_Conceded,Goals_Scored,Minutes,Own_Goals,Penalites_Missed,Red_Cards,Points,Yellow_Cards,Firstname,Lastname,Fixture_Rating,Delta_Goals,Delta_Assists,Delta_Goals_Conceded,Next_Points,Running_Assists,Running_Clean_Sheet,Running_xA,Running_xG,Running_xGC,Running_Goals_Conceded,Running_Goals_Scored,Running_Minutes,Running_Own_Goals,Running_Penalites_Missed,Running_Red_Cards,Running_Points,Running_Yellow_Cards,Running_Fixture_Rating,Running_Delta_Goals,Running_Delta_Assists,Running_Delta_Goals_Conceded,Running_Next_Points
0,0,0,0.10,0.56,1.50,1,0,90,0,0,0,2,0,Abdoulaye,Doucoure,3,-0.56,-0.10,0.50,2.0,0.00,0.00,0.100000,0.560000,1.500000,1.00,0.00,90.00,0.0,0.0,0.0,2.00,0.00,3.000000,-0.560000,-0.100000,0.500000,2.000000
1,0,0,0.03,0.09,3.11,4,0,90,0,0,0,2,0,Abdoulaye,Doucoure,5,-0.09,-0.03,-0.89,2.0,0.00,0.00,0.065000,0.325000,2.305000,2.50,0.00,90.00,0.0,0.0,0.0,2.00,0.00,4.000000,-0.325000,-0.065000,-0.195000,2.000000
2,0,0,0.10,0.21,1.16,1,0,90,0,0,0,2,0,Abdoulaye,Doucoure,3,-0.21,-0.10,0.16,8.0,0.00,0.00,0.076667,0.286667,1.923333,2.00,0.00,90.00,0.0,0.0,0.0,2.00,0.00,3.666667,-0.286667,-0.076667,-0.076667,4.000000
3,0,0,0.03,1.07,1.24,2,1,90,0,0,0,8,1,Abdoulaye,Doucoure,2,-0.07,-0.03,-0.76,2.0,0.00,0.00,0.065000,0.482500,1.752500,2.00,0.25,90.00,0.0,0.0,0.0,3.50,0.25,3.250000,-0.232500,-0.065000,-0.247500,3.500000
4,0,0,0.00,0.00,1.02,1,0,79,0,0,0,2,0,Abdoulaye,Doucoure,5,0.00,0.00,0.02,7.0,0.00,0.00,0.040000,0.342500,1.632500,2.00,0.25,87.25,0.0,0.0,0.0,3.50,0.25,3.750000,-0.092500,-0.040000,-0.367500,4.750000
5,0,0,0.05,0.12,1.04,1,1,90,0,0,0,7,0,Abdoulaye,Doucoure,2,0.88,-0.05,0.04,4.0,0.00,0.00,0.045000,0.350000,1.115000,1.25,0.50,87.25,0.0,0.0,0.0,4.75,0.25,3.000000,0.150000,-0.045000,-0.135000,5.250000
6,1,0,0.20,0.37,0.89,2,0,59,0,0,0,4,0,Abdoulaye,Doucoure,2,-0.37,0.80,-1.11,8.0,0.25,0.00,0.070000,0.390000,1.047500,1.50,0.50,79.50,0.0,0.0,0.0,5.25,0.25,2.750000,0.110000,0.180000,-0.452500,5.250000
7,0,1,0.22,1.14,0.72,0,1,90,0,0,0,8,0,Abdoulaye,Doucoure,3,-0.14,-0.22,0.72,2.0,0.25,0.25,0.117500,0.407500,0.917500,1.00,0.50,79.50,0.0,0.0,0.0,5.25,0.00,3.000000,0.092500,0.132500,-0.082500,5.250000
8,0,0,0.00,0.00,2.24,2,0,90,0,0,0,2,0,Abdoulaye,Doucoure,5,0.00,0.00,0.24,3.0,0.25,0.25,0.117500,0.407500,1.222500,1.25,0.50,82.25,0.0,0.0,0.0,5.25,0.00,3.000000,0.092500,0.132500,-0.027500,4.250000
9,0,1,0.01,0.19,0.66,0,0,90,0,0,0,3,0,Abdoulaye,Doucoure,4,-0.19,-0.01,0.66,1.0,0.25,0.50,0.107500,0.425000,1.127500,1.00,0.25,82.25,0.0,0.0,0.0,4.25,0.00,3.500000,-0.175000,0.142500,0.127500,3.500000
10,0,0,0.01,0.10,0.53,1,0,90,0,0,0,1,1,Abdoulaye,Doucoure,3,-0.10,-0.01,-0.47,11.0,0.00,0.50,0.060000,0.357500,1.037500,0.75,0.25,90.00,0.0,0.0,0.0,3.50,0.25,3.750000,-0.107500,-0.060000,0.287500,4.250000
11,1,0,0.02,0.74,2.24,2,1,90,0,0,0,11,1,Abdoulaye,Doucoure,4,0.26,0.98,0.24,1.0,0.25,0.25,0.010000,0.257500,1.417500,1.25,0.25,90.00,0.0,0.0,0.0,4.25,0.50,4.000000,-0.007500,0.240000,0.167500,4.000000
12,0,0,0.11,0.26,2.18,3,0,89,0,0,0,1,1,Abdoulaye,Doucoure,4,-0.26,-0.11,-0.82,3.0,0.25,0.25,0.037500,0.322500,1.402500,1.50,0.25,89.75,0.0,0.0,0.0,4.00,0.75,3.750000,-0.072500,0.212500,-0.097500,4.000000
13,0,1,0.03,0.00,0.71,0,0,90,0,0,0,3,0,Abdoulaye,Doucoure,2,0.00,-0.03,0.71,9.0,0.25,0.25,0.042500,0.275000,1.415000,1.50,0.25,89.75,0.0,0.0,0.0,4.00,0.75,3.250000,-0.025000,0.207500,-0.085000,6.000000
14,0,1,0.03,0.57,1.58,0,1,90,0,0,0,9,0,Abdoulaye,Doucoure,4,0.43,-0.03,1.58,10.0,0.25,0.50,0.047500,0.392500,1.677500,1.25,0.50,89.75,0.0,0.0,0.0,6.00,0.50,3.500000,0.107500,0.202500,0.427500,5.750000
15,0,1,0.01,0.20,0.93,0,1,90,0,0,0,10,0,Abdoulaye,Doucoure,4,0.80,-0.01,0.93,1.0,0.00,0.75,0.045000,0.257500,1.350000,0.75,0.50,89.75,0.0,0.0,0.0,5.75,0.25,3.500000,0.242500,-0.045000,0.600000,5.750000
16,0,0,0.01,0.00,0.48,0,0,45,0,0,0,1,0,Abdoulaye,Doucoure,2,0.00,-0.01,0.48,0.0,0.00,0.75,0.020000,0.192500,0.925000,0.00,0.50,78.75,0.0,0.0,0.0,5.75,0.00,3.000000,0.307500,-0.020000,0.925000,5.000000
17,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Abdoulaye,Doucoure,5,0.00,0.00,0.00,0.0,0.00,0.50,0.012500,0.192500,0.747500,0.00,0.50,56.25,0.0,0.0,0.0,5.00,0.00,3.750000,0.307500,-0.012500,0.747500,2.750000
18,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Abdoulaye,Doucoure,5,0.00,0.00,0.00,0.0,0.00,0.25,0.005000,0.050000,0.352500,0.00,0.25,33.75,0.0,0.0,0.0,2.75,0.00,4.000000,0.200000,-0.005000,0.352500,0.250000
19,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Abdoulaye,Doucoure,3,0.00,0.00,0.00,3.0,0.00,0.00,0.002500,0.000000,0.120000,0.00,0.00,11.25,0.0,0.0,0.0,0.25,0.00,3.750000,0.000000,-0.002500,0.120000,0.750000
20,0,1,0.01,0.04,1.11,0,0,90,0,0,0,3,0,Abdoulaye,Doucoure,5,-0.04,-0.01,1.11,0.0,0.00,0.25,0.002500,0.010000,0.277500,0.00,0.00,22.50,0.0,0.0,0.0,0.75,0.00,4.500000,-0.010000,-0.002500,0.277500,0.750000
21,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Abdoulaye,Doucoure,3,0.00,0.00,0.00,0.0,0.00,0.25,0.002500,0.010000,0.277500,0.00,0.00,22.50,0.0,0.0,0.0,0.75,0.00,4.000000,-0.010000,-0.002500,0.277500,0.750000
22,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Abdoulaye,Doucoure,5,0.00,0.00,0.00,0.0,0.00,0.25,0.002500,0.010000,0.277500,0.00,0.00,22.50,0.0,0.0,0.0,0.75,0.00,4.000000,-0.010000,-0.002500,0.277500,0.750000
23,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Abdoulaye,Doucoure,5,0.00,0.00,0.00,2.0,0.00,0.25,0.002500,0.010000,0.277500,0.00,0.00,22.50,0.0,0.0,0.0,0.75,0.00,4.500000,-0.010000,-0.002500,0.277500,0.500000
24,0,0,0.01,0.40,0.57,1,0,71,0,0,0,2,0,Abdoulaye,Doucoure,4,-0.40,-0.01,-0.43,3.0,0.00,0.00,0.002500,0.100000,0.142500,0.25,0.00,17.75,0.0,0.0,0.0,0.50,0.00,4.250000,-0.100000,-0.002500,-0.107500,1.250000
25,0,1,0.00,0.05,1.04,0,0,88,0,0,0,3,0,Abdoulaye,Doucoure,3,-0.05,0.00,1.04,2.0,0.00,0.25,0.002500,0.112500,0.402500,0.25,0.00,39.75,0.0,0.0,0.0,1.25,0.00,4.250000,-0.112500,-0.002500,0.152500,1.750000
26,0,0,0.03,0.25,1.28,2,0,90,0,0,0,2,0,Abdoulaye,Doucoure,4,-0.25,-0.03,-0.72,1.0,0.00,0.25,0.010000,0.175000,0.722500,0.75,0.00,62.25,0.0,0.0,0.0,1.75,0.00,4.000000,-0.175000,-0.010000,-0.027500,2.000000
27,0,0,0.01,0.17,2.21,2,0,60,0,0,0,1,1,Abdoulaye,Doucoure,4,-0.17,-0.01,0.21,2.0,0.00,0.25,0.012500,0.217500,1.275000,1.25,0.00,77.25,0.0,0.0,0.0,2.00,0.25,3.750000,-0.217500,-0.012500,0.025000,2.000000
28,0,0,0.13,0.00,1.56,1,0,71,0,0,0,2,0,Abdoulaye,Doucoure,3,0.00,-0.13,0.56,1.0,0.00,0.25,0.042500,0.117500,1.522500,1.25,0.00,77.25,0.0,0.0,0.0,2.00,0.25,3.500000,-0.117500,-0.042500,0.272500,1.500000
29,0,0,0.02,0.17,1.42,1,0,59,0,0,0,1,0,Abdoulaye,Doucoure,4,-0.17,-0.02,0.42,3.0,0.00,0.00,0.047500,0.147500,1.617500,1.50,0.00,70.00,0.0,0.0,0.0,1.50,0.25,3.750000,-0.147500,-0.047500,0.117500,1.750000
30,0,1,0.04,0.05,0.46,0,0,90,0,0,0,3,0,Abdoulaye,Doucoure,2,-0.05,-0.04,0.46,2.0,0.00,0.25,0.050000,0.097500,1.412500,1.00,0.00,70.00,0.0,0.0,0.0,1.75,0.25,3.250000,-0.097500,-0.050000,0.412500,2.000000
31,0,0,0.02,0.00,2.96,6,0,90,0,0,0,2,0,Abdoulaye,Doucoure,4,0.00,-0.02,-3.04,5.0,0.00,0.25,0.052500,0.055000,1.600000,2.00,0.00,77.50,0.0,0.0,0.0,2.00,0.00,3.250000,-0.055000,-0.052500,-0.400000,2.750000
32,1,1,0.01,0.00,0.85,0,0,90,0,0,0,5,1,Abdoulaye,Doucoure,2,0.00,0.99,0.85,3.0,0.25,0.50,0.022500,0.055000,1.422500,1.75,0.00,82.25,0.0,0.0,0.0,2.75,0.25,3.000000,-0.055000,0.227500,-0.327500,3.250000
33,0,1,0.13,0.14,2.06,0,0,90,0,0,0,3,0,Abdoulaye,Doucoure,5,-0.14,-0.13,2.06,3.0,0.25,0.75,0.050000,0.047500,1.582500,1.50,0.00,90.00,0.0,0.0,0.0,3.25,0.25,3.250000,-0.047500,0.200000,0.082500,3.250000
34,0,1,0.06,0.14,0.84,0,0,90,0,0,0,3,0,Abdoulaye,Doucoure,2,-0.14,-0.06,0.84,1.0,0.25,0.75,0.055000,0.070000,1.677500,1.50,0.00,90.00,0.0,0.0,0.0,3.25,0.25,3.250000,-0.070000,0.195000,0.177500,3.000000
35,0,0,0.01,0.04,0.56,1,0,53,0,0,0,1,0,Abdoulaye,Doucoure,2,-0.04,-0.01,-0.44,8.0,0.25,0.75,0.052500,0.080000,1.077500,0.25,0.00,80.75,0.0,0.0,0.0,3.00,0.25,2.750000,-0.080000,0.197500,0.827500,3.750000
36,0,1,0.05,1.63,0.35,0,1,68,0,0,0,8,0,Abdoulaye,Doucoure,2,-0.63,-0.05,0.35,1.0,0.00,0.75,0.062500,0.487500,0.952500,0.25,0.25,75.25,0.0,0.0,0.0,3.75,0.00,2.750000,-0.237500,-0.062500,0.702500,3.250000
37,0,0,0.02,0.00,2.76,2,0,90,0,0,0,1,1,Abdoulaye,Doucoure,5,0.00,-0.02,0.76,NaN,0.00,0.50,0.035000,0.452500,1.127500,0.75,0.25,75.25,0.0,0.0,0.0,3.25,0.25,2.750000,-0.202500,-0.035000,0.377500,3.333333

In [143]:
oblik()

(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)
(38, 38)

In [144]:
df_mid=pd.concat(dataframes)

In [145]:
df_mid

,Assists,Clean_Sheet,xA,xG,xGC,Goals_Conceded,Goals_Scored,Minutes,Own_Goals,Penalites_Missed,Red_Cards,Points,Yellow_Cards,Firstname,Lastname,Fixture_Rating,Delta_Goals,Delta_Assists,Delta_Goals_Conceded,Next_Points,Running_Assists,Running_Clean_Sheet,Running_xA,Running_xG,Running_xGC,Running_Goals_Conceded,Running_Goals_Scored,Running_Minutes,Running_Own_Goals,Running_Penalites_Missed,Running_Red_Cards,Running_Points,Running_Yellow_Cards,Running_Fixture_Rating,Running_Delta_Goals,Running_Delta_Assists,Running_Delta_Goals_Conceded,Running_Next_Points
0,0,0,0.10,0.56,1.50,1,0,90,0,0,0,2,0,Abdoulaye,Doucoure,3,-0.56,-0.10,0.50,2.0,0.0,0.0,0.100000,0.560000,1.500000,1.00,0.00,90.00,0.0,0.0,0.0,2.00,0.00,3.000000,-0.560000,-0.100000,0.500000,2.000000
1,0,0,0.03,0.09,3.11,4,0,90,0,0,0,2,0,Abdoulaye,Doucoure,5,-0.09,-0.03,-0.89,2.0,0.0,0.0,0.065000,0.325000,2.305000,2.50,0.00,90.00,0.0,0.0,0.0,2.00,0.00,4.000000,-0.325000,-0.065000,-0.195000,2.000000
2,0,0,0.10,0.21,1.16,1,0,90,0,0,0,2,0,Abdoulaye,Doucoure,3,-0.21,-0.10,0.16,8.0,0.0,0.0,0.076667,0.286667,1.923333,2.00,0.00,90.00,0.0,0.0,0.0,2.00,0.00,3.666667,-0.286667,-0.076667,-0.076667,4.000000
3,0,0,0.03,1.07,1.24,2,1,90,0,0,0,8,1,Abdoulaye,Doucoure,2,-0.07,-0.03,-0.76,2.0,0.0,0.0,0.065000,0.482500,1.752500,2.00,0.25,90.00,0.0,0.0,0.0,3.50,0.25,3.250000,-0.232500,-0.065000,-0.247500,3.500000
4,0,0,0.00,0.00,1.02,1,0,79,0,0,0,2,0,Abdoulaye,Doucoure,5,0.00,0.00,0.02,7.0,0.0,0.0,0.040000,0.342500,1.632500,2.00,0.25,87.25,0.0,0.0,0.0,3.50,0.25,3.750000,-0.092500,-0.040000,-0.367500,4.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,0,0,0.04,0.00,1.66,1,0,62,0,0,0,2,0,Yves,Bissouma,4,0.00,-0.04,0.66,1.0,0.0,0.0,0.025000,0.035000,1.297500,1.25,0.00,47.25,0.0,0.0,0.0,1.00,0.25,3.750000,-0.035000,-0.025000,0.047500,1.000000
34,0,0,0.04,0.04,3.22,4,0,90,0,0,0,1,1,Yves,Bissouma,5,-0.04,-0.04,-0.78,2.0,0.0,0.0,0.027500,0.010000,1.865000,2.00,0.00,58.50,0.0,0.0,0.0,1.00,0.50,4.500000,-0.010000,-0.027500,-0.135000,1.500000
35,0,0,0.05,0.00,0.75,1,0,74,0,0,0,2,0,Yves,Bissouma,2,0.00,-0.05,-0.25,0.0,0.0,0.0,0.037500,0.010000,1.435000,1.50,0.00,63.00,0.0,0.0,0.0,1.50,0.25,4.000000,-0.010000,-0.037500,-0.065000,1.250000
36,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Yves,Bissouma,5,0.00,0.00,0.00,0.0,0.0,0.0,0.032500,0.010000,1.407500,1.50,0.00,56.50,0.0,0.0,0.0,1.25,0.25,4.000000,-0.010000,-0.032500,-0.092500,0.750000
37,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,Yves,Bissouma,2,0.00,0.00,0.00,NaN,0.0,0.0,0.022500,0.010000,0.992500,1.25,0.00,41.00,0.0,0.0,0.0,0.75,0.25,3.500000,-0.010000,-0.022500,-0.257500,0.666667

In [146]:
df_mid.shape

(3382, 38)

In [147]:
df_mid.to_csv("vezni.csv")